linters-settings:
  custom:
    godoxwithregexp:
      # Path is required
      path: godoxwithregexp.so
      # Description is optional
      description: Tool for detection of TODO and other comment keywords with regular expression.
      # Original-url is optional, and is only used for documentation purposes.
      original-url: github.com/SilverdewBaker/godox-with-regexp

linters:
  disable-all: true
  enable:
    - godoxwithregexp
    # Typecheck is how golangci-lint reports compile errors, so should always be enabled.
    - typecheck
